--CREATE TABLE Автор(Код_автора BIGINT PRIMARY KEY IDENTITY,Фамилия NVARCHAR(100) NOT NULL,
--Имя NVARCHAR(100) NOT NULL,
--Страна NVARCHAR(100) NOT NULL,
--Год DATE NOT NULL)


--CREATE TABLE Рецепт (Код_рецепта BIGINT PRIMARY KEY IDENTITY ,
--Код_продукта BIGINT FOREIGN KEY REFERENCES PRODUKT(Id),
--Код_автора BIGINT FOREIGN KEY REFERENCES Автор(Код),
--Номер INT NOT NULL, Название NVARCHAR(100) NOT NULL, Описание NVARCHAR(500) NOT NULL);


USE [C:\USERS\KANDR\SOURCE\REPOS\KURSOVAY\KURSOVAY\DATABASE1.MDF]
INSERT INTO Поставщик(Название,Адрес,Телефон)
VALUES('Хлебзавод','Воронеж',562395478) ; 

